---
repos:
    # 1 Preprocessing & Code Hygiene Checks
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: check-yaml
          - id: mixed-line-ending
          - id: end-of-file-fixer
            exclude: "^app/static/css/dist/output\\.css$|app/translations/.*"
          - id: trailing-whitespace
          - id: check-merge-conflict
          - id: check-added-large-files
            args: ['--maxkb=1024']  # 2 MB limit
          - id: detect-private-key
          - id: debug-statements
          - id: requirements-txt-fixer

    # 2 Security & Secret Scanning
    - repo: https://github.com/gitleaks/gitleaks
      rev: v8.24.2
      hooks:
          - id: gitleaks
            args: [--verbose]

    # 3 Code Formatting (Must run before type-checking & linting)
    - repo: https://github.com/psf/black
      rev: 25.1.0
      hooks:
          - id: black
            args: [--line-length=79]

    - repo: https://github.com/PyCQA/isort
      rev: 6.0.1
      hooks:
          - id: isort
            name: isort (python)
            args: [--profile=black]

    # 4 Static Analysis & Security Checks
    - repo: https://github.com/PyCQA/bandit
      rev: 1.8.3
      hooks:
          - id: bandit

    # 5 Python Code Modernization
    - repo: https://github.com/asottile/pyupgrade
      rev: v3.19.1
      hooks:
          - id: pyupgrade

    # 6 Spell Checking (Post-Processing Step)
    - repo: https://github.com/codespell-project/codespell
      rev: v2.4.1
      hooks:
          - id: codespell
            args:
                [
                    '--skip=utils/disposable_email_blocklist.conf,app/static/js/htmx.min.js',
                    '--write-changes',
                ]
