---
services:
  mongodb:
    image: mongo:8
    container_name: mongodb_swea
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: swea
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7
    container_name: redis_swea
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local
