---
services:
  postgres:
    image: postgres:latest
    container_name: postgres_swea
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=swea_db
      - POSTGRES_PASSWORD=swea_pass
      - POSTGRES_USER=swea_user
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_swea
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  pg_data:
    driver: local
  redis_data:
    driver: local
