"""Initial setup

Revision ID: 9c23a0119cc5
Revises: 
Create Date: 2025-02-22 22:08:25.772325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c23a0119cc5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('courses',
    sa.Column('title', sa.JSON(), nullable=False),
    sa.Column('course_name', sa.JSON(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('description', sa.JSON(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('members',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('university_department', sa.String(length=255), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('news',
    sa.Column('title', sa.JSON(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('description', sa.JSON(), nullable=False),
    sa.Column('url_redirect', sa.String(length=255), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('podcasts',
    sa.Column('title', sa.JSON(), nullable=False),
    sa.Column('podcast_name', sa.JSON(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('description', sa.JSON(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('projects',
    sa.Column('title', sa.JSON(), nullable=False),
    sa.Column('author', sa.JSON(), nullable=False),
    sa.Column('date_of_completion', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ongoing', 'completed', name='project_status'), nullable=False),
    sa.Column('content', sa.ARRAY(sa.JSON()), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('hero_image', sa.String(length=255), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('testimonials', sa.ARRAY(sa.JSON()), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('research',
    sa.Column('title', sa.JSON(), nullable=False),
    sa.Column('author', sa.JSON(), nullable=False),
    sa.Column('date_of_completion', sa.Date(), nullable=True),
    sa.Column('content', sa.ARRAY(sa.JSON()), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('hero_image', sa.String(length=255), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('testimonials', sa.ARRAY(sa.JSON()), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('teams',
    sa.Column('name', sa.JSON(), nullable=False),
    sa.Column('role', sa.JSON(), nullable=False),
    sa.Column('bio', sa.JSON(), nullable=False),
    sa.Column('socials', sa.JSON(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('course_members',
    sa.Column('course_uuid', sa.String(length=36), nullable=False),
    sa.Column('member_uuid', sa.String(length=36), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_uuid'], ['courses.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_uuid'], ['members.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('course_uuid', 'member_uuid', 'uuid')
    )
    op.create_table('podcast_members',
    sa.Column('podcast_uuid', sa.String(length=36), nullable=False),
    sa.Column('member_uuid', sa.String(length=36), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_uuid'], ['members.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['podcast_uuid'], ['podcasts.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('podcast_uuid', 'member_uuid', 'uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('podcast_members')
    op.drop_table('course_members')
    op.drop_table('users')
    op.drop_table('teams')
    op.drop_table('research')
    op.drop_table('projects')
    op.drop_table('podcasts')
    op.drop_table('news')
    op.drop_table('members')
    op.drop_table('courses')
    op.drop_table('contacts')
    # ### end Alembic commands ###
